<%--To avoid the overriding of any manual code changes upon subsequent code generations, disable "Generate JSP Files" option in the Adaptor model.--%>
<!DOCTYPE html>
<%--
 Copyright (c) 2011, 2012, 2017 IBM Corporation and others.

 All rights reserved. This program and the accompanying materials
 are made available under the terms of the Eclipse Public License v1.0
 and Eclipse Distribution License v. 1.0 which accompanies this distribution.

 The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 and the Eclipse Distribution License is available at
 http://www.eclipse.org/org/documents/edl-v10.php.

 Contributors:

  Sam Padgett     - initial API and implementation
  Michael Fiedler - adapted for OSLC4J
  Jad El-khoury   - initial implementation of code generator (422448)
  Frédéric Loiret - Switch the template to Bootstrap (519699)

 This file is generated by org.eclipse.lyo.oslc4j.codegenerator
--%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<%@page import="org.eclipse.lyo.oslc4j.core.model.Link" %>
<%@page import="org.eclipse.lyo.oslc4j.core.model.ServiceProvider"%>
<%@page import="java.net.URI"%>
<%@page import="java.util.Date"%>
<%@page import="java.util.HashSet"%>
<%@page import="java.util.List"%>
<%@page import="java.util.Iterator"%>
<%@page import="com.sample.rm.resources.Requirement"%>

<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>

<%
  Requirement aRequirement = (Requirement) request.getAttribute("aRequirement");
%>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title><%= aRequirement.toString() %></title>

  <link href="<c:url value="/static/css/bootstrap-4.0.0-beta.min.css"/>" rel="stylesheet">
  <link href="<c:url value="/static/css/adaptor.css"/>" rel="stylesheet">

  <script src="<c:url value="/static/js/jquery-3.2.1.min.js"/>"></script>
  <script src="<c:url value="/static/js/popper-1.11.0.min.js"/>"></script>
  <script src="<c:url value="/static/js/bootstrap-4.0.0-beta.min.js"/>"></script>
  <script src="<c:url value="/static/js/preview.js"/>"></script>
  <script src="<c:url value="/static/js/ui-preview-helper.js"/>"></script>
</head>

<body>

<!-- Begin page content -->
<div>
        <div>
          <dl class="dl-horizontal">
            <dt>identifier</dt>
            <dd>
            <%
            if (aRequirement.getIdentifier() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aRequirement.getIdentifier().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="dl-horizontal">
            <dt>title</dt>
            <dd>
            <%
            if (aRequirement.getTitle() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aRequirement.getTitle().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="dl-horizontal">
            <dt>description</dt>
            <dd>
            <%
            if (aRequirement.getDescription() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aRequirement.getDescription().toString());
            }
            %>
            
            </dd>
          </dl>
        </div>
      </div>
</body>
</html>
