<%--To avoid the overriding of any manual code changes upon subsequent code generations, disable "Generate JSP Files" option in the Adaptor model.--%>
<!DOCTYPE html>
<%--
 Copyright (c) 2011, 2012 IBM Corporation and others.

 All rights reserved. This program and the accompanying materials
 are made available under the terms of the Eclipse Public License v1.0
 and Eclipse Distribution License v. 1.0 which accompanies this distribution.

 The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 and the Eclipse Distribution License is available at
 http://www.eclipse.org/org/documents/edl-v10.php.

 Contributors:

  Sam Padgett     - initial API and implementation
  Michael Fiedler - adapted for OSLC4J
  Jad El-khoury   - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)

 This file is generated by org.eclipse.lyo.oslc4j.codegenerator
--%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<%@page import="org.eclipse.lyo.oslc4j.core.model.ServiceProvider"%>
<%@page import="com.sample.rm.resources.Requirement"%>
<%@page import="org.eclipse.lyo.oslc4j.core.OSLC4JUtils"%>
<%@page import="javax.ws.rs.core.UriBuilder"%>

<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>

<%
  String selectionUri = (String) request.getAttribute("selectionUri");
  String resourceTypeLabel = (String) request.getAttribute("resourceTypeLabel");
%>

<html> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8"> 
        <link rel="stylesheet" href="<c:url value="/static/dist/oslc-ui/styles.css"/>"> 
    </head> 
    <body> 
        <oslc-selector selection-uri="<%=selectionUri%>" fields='["oslc:label"]' no-data-text="No <%=resourceTypeLabel%> found" search-placeholder-text="Search for resources of type: <%=resourceTypeLabel%>"></oslc-selector>
        <script src="<c:url value="/static/dist/oslc-ui/runtime-es2015.js"/>" type="module"></script> 
        <script src="<c:url value="/static/dist/oslc-ui/runtime-es5.js"/>" nomodule defer></script> 
        <script src="<c:url value="/static/dist/oslc-ui/polyfills-es5.js"/>" nomodule defer></script> 
        <script src="<c:url value="/static/dist/oslc-ui/polyfills-es2015.js"/>" type="module"></script> 
        <script src="<c:url value="/static/dist/oslc-ui/main-es2015.js"/>" type="module"></script> 
        <script src="<c:url value="/static/dist/oslc-ui/main-es5.js"/>" nomodule defer></script> 
    </body> 
</html>