<%--To avoid the overriding of any manual code changes upon subsequent code generations, disable "Generate JSP Files" option in the Adaptor model.--%>
<!DOCTYPE html>
<%--
 Copyright (c) 2020 Contributors to the Eclipse Foundation
 
 See the NOTICE file(s) distributed with this work for additional
 information regarding copyright ownership.
 
 This program and the accompanying materials are made available under the
 terms of the Eclipse Distribution License 1.0 which is available at
 http://www.eclipse.org/org/documents/edl-v10.php.
 
 SPDX-License-Identifier: BSD-3-Simple

 This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
--%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page import="java.util.ArrayList" %>
<%@ page import="java.util.List" %>
<%@ page import="java.net.URI" %>
<%@ page import="java.net.URLEncoder" %>
<%@ page import="org.eclipse.lyo.oslc4j.core.model.Service" %>
<%@ page import="org.eclipse.lyo.oslc4j.core.model.ServiceProvider" %>
<%@ page import="org.eclipse.lyo.oslc4j.core.model.Dialog" %>
<%@ page import="org.eclipse.lyo.oslc4j.core.model.CreationFactory" %>
<%@ page import="org.eclipse.lyo.oslc4j.core.model.ResourceShape" %>
<%@ page import="org.eclipse.lyo.oslc4j.core.model.QueryCapability" %>
<%@page import="javax.ws.rs.core.UriBuilder"%>
<%@page import="org.eclipse.lyo.oslc4j.core.OSLC4JUtils"%>

<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>

<%
ServiceProvider serviceProvider = (ServiceProvider)request.getAttribute("serviceProvider");
Service[] services = (Service[])request.getAttribute("services");
String catalogUrl = UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path("/catalog/singleton").build().toString();
%>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= serviceProvider.getTitle() %></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="<c:url value="/static/css/adaptor.css"/>" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
      <a class="navbar-brand" href="<c:url value="/"/>"><%= application.getServletContextName() %></a>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item"><a class="nav-link" href="<c:url value="<%= catalogUrl %>"/>">Service Provider Catalog</a></li>
        <li class="nav-item"><a class="nav-link" href="<c:url value="/swagger-ui/index.jsp"/>">Swagger UI</a></li>
      </ul>
  </nav>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="<%= catalogUrl %>">Service Provider Catalog</a></li>
      <li class="breadcrumb-item"><a href="http://localhost:8083/adaptor-rm/services/service1/requirements/query">Service Provider 1</a></li>

    </ol>
  </nav>

  <div class="provider-container">
    <div class="page-header">
      <h4><%= serviceProvider.getTitle() %></h4>
      <p><%= serviceProvider.getDescription() %></p>
    </div>
    <div class="provider-container-body">
    <%!
    String listResourceTypes(URI[] resourceTypes) {
        List<String> rs = new ArrayList<String>();
        for(URI resourceType : resourceTypes) {
            String[] split = resourceType.toString().split("[#/]+");
            String shortName = (split.length > 1) ? split[split.length -1] : resourceType.toString();
            rs.add("<a href=\"" + resourceType + "\">" + shortName + "</a>");
        }
        return String.join(", ", rs);
    }         
    %>
    <% if (services.length == 0) {%>
        <div class="alert alert-primary" role="alert">
            <h4 class="alert-heading">No OSLC Services Defined for this Service Provider!</h4>
            <hr>
            <p>
                Define some OSLC services for your Service Provider in your model. 
                Then re-generate to obtain access to these services.
            </p>
        </div>
        <div class="card">

    <% } %>
    <%for (int serviceIndex = 0; serviceIndex < services.length; serviceIndex++) {%>
    <% 
    URI domain = services[serviceIndex].getDomain();
    Dialog[] selectionDialogs = services[serviceIndex].getSelectionDialogs();
    Dialog[] creationDialogs = services[serviceIndex].getCreationDialogs();
    CreationFactory[] creationFactories = services[serviceIndex].getCreationFactories();
    QueryCapability[] queryCapabilities= services[serviceIndex].getQueryCapabilities();
    %>
      <div class="card-body">
        <h5>OSLC Service</h5>
      <p class="text-sm"> Domain: <a href="<%=domain%>"><%=domain%></a></p>
    <h5>Capabilities</h5>
    <% if(selectionDialogs.length > 0) {%>
    <div class="section">
    <%
    for (int selectionDialogIndex = 0; selectionDialogIndex < selectionDialogs.length; selectionDialogIndex++) {
        String selectionDialog = selectionDialogs[selectionDialogIndex].getDialog().toString();
%>

<!--  Selection dialogue -->
    <h6><span class="badge badge-primary"><i class="bi bi-hand-index-thumb"></i></span>
         <span class="badge badge-info"><i class="bi bi-display"></i></span>
         <a href="<%=request.getContextPath()%>/com/sample/rm/selectiondialogsampleclient.jsp?selectionUri=<%= URLEncoder.encode(selectionDialog.toString(), "UTF-8") %>">
        Selection Dialogue</a></h6>
    <p>Dialog Url: <a href="<%= selectionDialog %>""><%= selectionDialog %></a><i class="hover-bg-light-blue p-2 bi bi-clipboard-fill" onclick="handleOnClick(this)"></i></p>
         <p>Resource Type: {<%= listResourceTypes(selectionDialogs[selectionDialogIndex].getResourceTypes()) %>}</p>
         <p>hintHeight: 250px</p>
         <p>hintWidth: 250px</p>
            <%}%>
    </div>
    <%}%>

    <!-- Resource Creation Dialogue -->
 
    <% if(creationDialogs.length > 0) {%>
      <div class="section">
        <%
        for (int creationDialogIndex = 0; creationDialogIndex < creationDialogs.length; creationDialogIndex++) {
            String creationDialog = creationDialogs[creationDialogIndex].getDialog().toString();
    %>
        <h6><span class="badge badge-success"><i class="bi bi-patch-plus"></i></span>
           <span class="badge badge-info"><i class="bi bi-display"></i></span> 
           <a href="<%= creationDialog %>">Creation Dialogue</a></h6>
           <p>Dialog Url: <a href="<%= creationDialog %>"><%= creationDialog %></a><i class="p-2 bi bi-clipboard-fill" onclick="handleOnClick(this)"></i></p>
          <p>Resource Type: {<%= listResourceTypes(creationDialogs[creationDialogIndex].getResourceTypes()) %>}</p>
    <%}%>
    </div>
    <%}%>

    <!-- Resource creation Factory -->
    <% if(creationFactories.length > 0) {%>
      <div class="section">
        <%
        for (int creationFactoryIndex = 0; creationFactoryIndex < creationFactories.length; creationFactoryIndex++) {
            String creationFactory = creationFactories[creationFactoryIndex].getCreation().toString();
    %>
        <h6><span class="badge badge-success"><i class="bi bi-patch-plus"></i></span>
          <span class="badge badge-info"><i class="bi bi-display"></i></span>
          <a href="<%= creationFactory %>">Creation Factory</a></h6>
          <p>Factory Url: <a href="<%= creationFactory %>"><%= creationFactory %></a><i class="p-2 bi bi-clipboard-fill" onclick="handleOnClick(this)"></i></p>
          <p>Resource Type: {<%= listResourceTypes(creationFactories[creationFactoryIndex].getResourceTypes()) %>}</p>
    <%}%>
    </div>
    <%}%>

    <!-- resource query capabilities -->
    <% if(queryCapabilities.length > 0) {%>
      <div class="section">
        <% 
        for (int queryCapabilityIndex = 0; queryCapabilityIndex < queryCapabilities.length; queryCapabilityIndex++) {
          QueryCapability qc = queryCapabilities[queryCapabilityIndex];
          String queryCapability = qc.getQueryBase().toString();
          String queryShape = queryCapabilities[queryCapabilityIndex].getResourceShape().toString();
          %>
          
        <h6><span class="badge badge-primary"><i class="bi bi-search"></i></span>
          <span class="badge badge-info"><i class="bi bi-display"></i></span>
          <a href="<%= queryCapability %>">Query Capabilities</a></h6>
          <p>Resource Shape: <a href="<%= queryShape %>"><%= queryShape %></a><i class="p-2 bi bi-clipboard-fill" onclick="handleOnClick(this)"></i></p>
          <p>Resource Type: {<%= listResourceTypes(queryCapabilities[queryCapabilityIndex].getResourceTypes()) %>}</p>
    <%}%>
    </div>
    <%}%>
    <c:if test="<%=serviceIndex + 1 < services.length%>">
    </c:if>
    </div>
    <%}%>
  </div>
</div>
</div>
  <footer class="footer">
      <p class="text-muted">
        OSLC Adaptor was generated using <a href="http://eclipse.org/lyo">Eclipse Lyo</a>.
      </p>
  </footer>
  <script>
    const handleOnClick = (e) => {navigator.clipboard.writeText(e.previousSibling.innerHTML);
}
    </script>
</body>
</html>
