// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package com.sample.rm.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface OslcDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String OSLC_DOMAINS_DOMAIN = "http://open-services.net/ns/core#";
    public static String OSLC_DOMAINS_NAMSPACE = "http://open-services.net/ns/core#";
    public static String OSLC_DOMAINS_NAMSPACE_PREFIX = "oslc";

    public static String PROVIDERTOTRS_PATH = "providerToTRS";
    public static String PROVIDERTOTRS_NAMESPACE = OSLC_DOMAINS_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PROVIDERTOTRS_LOCALNAME = "ProviderToTRS"; //localName of the rdfs:class the resource describes
    public static String PROVIDERTOTRS_TYPE = PROVIDERTOTRS_NAMESPACE + PROVIDERTOTRS_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String SP_PATH = "sP";
    public static String SP_NAMESPACE = OSLC_DOMAINS_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String SP_LOCALNAME = "SP"; //localName of the rdfs:class the resource describes
    public static String SP_TYPE = SP_NAMESPACE + SP_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String TRS_PATH = "tRS";
    public static String TRS_NAMESPACE = OSLC_DOMAINS_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String TRS_LOCALNAME = "TRS"; //localName of the rdfs:class the resource describes
    public static String TRS_TYPE = TRS_NAMESPACE + TRS_LOCALNAME; //fullname of the rdfs:class the resource describes
}
