version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Build OSLC RM sample adaptor
          command: cd adaptor-rm-webapp && mvn clean verify -B
      - run:
          name: Build OSLC QM (Testing) sample adaptor
          command: cd adaptor-testing-webapp && mvn clean verify -B