// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package com.sample.rm.exception;

import javax.servlet.http.HttpServletResponse;

// Start of user code imports
// End of user code

// Start of user code pre_class_code
// End of user code

/* Holds a status code and error message for an error response. */
public class RestException extends Exception {
    private int statusCode;
    private String message;

    // Start of user code class_attributes
    // End of user code

    // Start of user code class_methods
    // End of user code

    public RestException(int statusCode, String message) {
        this.statusCode = statusCode;
        this.message = message;
    }
    
    public RestException(Throwable t) {
        this(t, HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    
    public RestException(Throwable t, int statusCode) {
        super(t);
        this.message = t.getMessage();
        this.statusCode = statusCode;
    }

    public int getStatusCode() {
        return statusCode;
    }
    
    public void setStatusCode(int statusCode) {
        this.statusCode = statusCode;
    }
    
    public String getMessage() {
        return message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
}
