// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package com.sample.rm.exception;

import javax.servlet.http.HttpServletResponse;

// Start of user code imports
// End of user code

// Start of user code pre_class_code
// End of user code

/* Corresponds to an HTTP 401 response. */
public class UnauthorizedException extends RestException {
    // Start of user code class_attributes
    // End of user code

    // Start of user code class_methods
    // End of user code

    public UnauthorizedException() {
        super(HttpServletResponse.SC_UNAUTHORIZED,
                "You must authenticate for this request.");
    }
    
    public UnauthorizedException(String message) {
        super(HttpServletResponse.SC_UNAUTHORIZED, message);
    }
    
    public UnauthorizedException(Throwable t) {
        super(t, HttpServletResponse.SC_UNAUTHORIZED);
    }
}
