// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2017 Jad El-khoury.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Jad El-khoury       - initial implementation of main class for client-only adaptor
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package com.sample.client;

import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;
import java.net.MalformedURLException;

import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.model.ResourceShape;
import org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory;
import org.eclipse.lyo.oslc4j.core.model.ServiceProviderCatalog;
import org.eclipse.lyo.oslc4j.provider.jena.JenaModelHelper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.apache.jena.rdf.model.Model;

import com.sample.client.resources.Requirement;
import com.sample.client.resources.TestScript;
import com.sample.client.clients.GenericRequiredAdaptorClient;

// Start of user code imports
// End of user code

// Start of user code pre_class_code
// End of user code

public class OslcMainApplication {

    private static String baseUrl = "http://localhost:8080";
    private static String servletUrlPattern = "services/";
    private static final Logger logger = LoggerFactory.getLogger(OslcMainApplication.class);

    // Start of user code class_attributes
    // End of user code

    // Start of user code class_methods
    // End of user code

    public static void main(String[] args) throws Exception 
    {
        // Start of user code main
        //TODO: Replace/adjust this default main function as necessary.
        //All manual changes in this "protected" user code area will NOT be overwritten upon subsequent code generations.
        //To revert to the default generated content, delete all content in this file, and then re-generate.
    	logger.info("Starting OslcMainApplication client");
        try {
        	logger.debug("Setting public URI to {}", baseUrl);
            OSLC4JUtils.setPublicURI(baseUrl);
            logger.debug("Setting servlet path to {}", servletUrlPattern);
            OSLC4JUtils.setServletPath(servletUrlPattern);
        } catch (MalformedURLException e) {
            logger.error("Application encountered MalformedURLException.", e);
        } catch (IllegalArgumentException e) {
            logger.error("Application encountered IllegalArgumentException.", e);
        }

        logger.trace("Fetching OSLC Service Provider Catalog");
        ServiceProviderCatalog genericRequiredAdaptorClientCatalog = GenericRequiredAdaptorClient.getServiceProviderCatalog();

        List<ResourceShape> shapes = new ArrayList<ResourceShape>();
        shapes.add(Requirement.createResourceShape());
        shapes.add(TestScript.createResourceShape());
        Model model = JenaModelHelper.createJenaModel(shapes.toArray());
        String fileName = "resourceShapes.ttl";
        FileOutputStream output = new FileOutputStream(new File(fileName));
        model.write(output, "TURTLE" );
    }
    // End of user code
}
