// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2017 Jad El-khoury.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Jad El-khoury       - initial implementation of main class for client-only adaptor
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package com.sample.client;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.net.MalformedURLException;

import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.model.ResourceShape;
import org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory;
import org.eclipse.lyo.oslc4j.core.model.ServiceProviderCatalog;
import org.eclipse.lyo.oslc4j.provider.jena.JenaModelHelper;

import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;

import com.sample.client.resources.Requirement;
import com.sample.client.resources.TestScript;
import com.sample.client.clients.GenericRequiredAdaptorClient;

// Start of user code imports
import org.eclipse.lyo.oslc.domains.cm.ChangeRequest;
// End of user code

// Start of user code pre_class_code
// End of user code

public class OslcMainApplication {

    private static String baseUrl = "http://localhost:8080";
    private static String servletUrlPattern = "services/";
    private static final Logger logger = Logger.getLogger(OslcMainApplication.class.getName());

    // Start of user code class_attributes
    // End of user code

    // Start of user code class_methods
    // End of user code

    public static void main(String[] args) throws Exception 
    {
        // Start of user code main
        //TODO: Replace/adjust this default main function as necessary.
        //All manual changes in this "protected" user code area will NOT be overwritten upon subsequent code generations.
        //To revert to the default generated content, delete all content in this file, and then re-generate.
        try {
            OSLC4JUtils.setPublicURI(baseUrl);
            OSLC4JUtils.setServletPath(servletUrlPattern);
        } catch (MalformedURLException e) {
            logger.log(Level.SEVERE, "Application encountered MalformedURLException.", e);
        } catch (IllegalArgumentException e) {
            logger.log(Level.SEVERE, "Application encountered IllegalArgumentException.", e);
        }

        String in = "resource1.xml";
        FileInputStream input = new FileInputStream(new File(in));
        Model model1 = ModelFactory.createDefaultModel();
        model1.read(in, null);
        ChangeRequest[] crs = JenaModelHelper.unmarshal(model1, ChangeRequest.class);
        
        System.out.println(crs.length);

    
    }
    // End of user code
}
