name: 'CI'

on:
  push:
    branches:
      - 'main-*'
  pull_request:
    branches: 
      - 'main-*'
  schedule:
    - cron: "30 4,20 * * 4,5,6" # catch SNAPSHOT breaking changes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        jdk: ['8', '11', '17', '21']
        distribution: ['temurin']
        experimental: [false]
        include:
          - jdk: '23'
            distribution: 'zulu'
            experimental: true
          - jdk: '24-ea'
            distribution: 'zulu'
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.jdk }}
      
      - name: 'Build RM Sample'
        run: |
          mvn -B clean verify --file adaptor-rm-webapp/pom.xml
      
      - name: 'Build :: Testing Sample'
        run: |
          mvn -B clean verify --file adaptor-testing-webapp/pom.xml
      
      - name: 'Build :: Sample Client'
        run: |
          mvn -B clean verify --file adaptor-testing-webapp/pom.xml
